<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>21 An Introduction to Spatial Data in R | Data Management and Reproducible Science</title>
<meta name="author" content="Claire S Teitelbaum">
<meta name="description" content="21.1 Objectives Understand the structures of spatial data in R, including both vector (points, lines, polygons) and raster (gridded) data Be familiar with the core R packages for spatial data (sf,...">
<meta name="generator" content="bookdown 0.43 with bs4_book()">
<meta property="og:title" content="21 An Introduction to Spatial Data in R | Data Management and Reproducible Science">
<meta property="og:type" content="book">
<meta property="og:description" content="21.1 Objectives Understand the structures of spatial data in R, including both vector (points, lines, polygons) and raster (gridded) data Be familiar with the core R packages for spatial data (sf,...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="21 An Introduction to Spatial Data in R | Data Management and Reproducible Science">
<meta name="twitter:description" content="21.1 Objectives Understand the structures of spatial data in R, including both vector (points, lines, polygons) and raster (gridded) data Be familiar with the core R packages for spatial data (sf,...">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><script src="libs/bs3compat-0.8.0/transition.js"></script><script src="libs/bs3compat-0.8.0/tabs.js"></script><script src="libs/bs3compat-0.8.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="libs/tabwid-1.1.3/tabwid.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">Data Management and Reproducible Science</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"><span class="header-section-number">1</span> Course overview</a></li>
<li><a class="" href="intro.html"><span class="header-section-number">2</span> Introduction: The What and Why of Reproducible Science</a></li>
<li><a class="" href="basics.html"><span class="header-section-number">3</span> Getting Started with R</a></li>
<li><a class="" href="importexport.html"><span class="header-section-number">4</span> Data Structures and Importing Data</a></li>
<li><a class="" href="troubleshooting.html"><span class="header-section-number">5</span> Troubleshooting in R</a></li>
<li><a class="" href="filter-select-mutate.html"><span class="header-section-number">6</span> Data Manipulation with R, Part 1</a></li>
<li><a class="" href="nums-chrs.html"><span class="header-section-number">7</span> Numbers, Characters, and Factors in R</a></li>
<li><a class="" href="lubridate.html"><span class="header-section-number">8</span> Dates and Times in R</a></li>
<li><a class="" href="manipulation.html"><span class="header-section-number">9</span> Data Manipulation with R, Part 2</a></li>
<li><a class="" href="style.html"><span class="header-section-number">10</span> Coding Best Practices</a></li>
<li><a class="" href="ggplot.html"><span class="header-section-number">11</span> Data Visualization with ggplot2</a></li>
<li><a class="" href="data-presentation.html"><span class="header-section-number">12</span> Customizing Graphics with ggplot2</a></li>
<li><a class="" href="tables.html"><span class="header-section-number">13</span> Creating and Designing Data Tables</a></li>
<li><a class="" href="git.html"><span class="header-section-number">14</span> Version Control with Git and GitHub</a></li>
<li><a class="" href="github.html"><span class="header-section-number">15</span> Collaboration with GitHub (or friends)</a></li>
<li><a class="" href="markdown.html"><span class="header-section-number">16</span> Reproducible Reports with R Markdown and Quarto</a></li>
<li><a class="" href="qaqc.html"><span class="header-section-number">17</span> Data Cleaning in R</a></li>
<li><a class="" href="for-if.html"><span class="header-section-number">18</span> Iterating and Conditioning: for Loops and if Statements</a></li>
<li><a class="" href="functions.html"><span class="header-section-number">19</span> Writing Your Own Functions</a></li>
<li><a class="" href="lists.html"><span class="header-section-number">20</span> Complex Data Structures in R</a></li>
<li><a class="active" href="spatial.html"><span class="header-section-number">21</span> An Introduction to Spatial Data in R</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="spatial" class="section level1" number="21">
<h1>
<span class="header-section-number">21</span> An Introduction to Spatial Data in R<a class="anchor" aria-label="anchor" href="#spatial"><i class="fas fa-link"></i></a>
</h1>
<div id="objectives-18" class="section level2" number="21.1">
<h2>
<span class="header-section-number">21.1</span> Objectives<a class="anchor" aria-label="anchor" href="#objectives-18"><i class="fas fa-link"></i></a>
</h2>
<ul>
<li>Understand the structures of spatial data in R, including both vector (points,
lines, polygons) and raster (gridded) data</li>
<li>Be familiar with the core R packages for spatial data (<code>sf</code>, <code>terra</code>)</li>
<li>Plot spatial data using <code>ggplot2</code>
</li>
<li>Work with both geographic and projected coordinates in R</li>
</ul>
</div>
<div id="additional-reading-15" class="section level2" number="21.2">
<h2>
<span class="header-section-number">21.2</span> Additional reading<a class="anchor" aria-label="anchor" href="#additional-reading-15"><i class="fas fa-link"></i></a>
</h2>
<p>Edzer Pebsma, and Roger Bivand. Spatial Data Science With Applications in R. Chapter 7.1: Package sf. Available: <a href="https://r-spatial.org/book/07-Introsf.html#sec-sfintro" class="uri">https://r-spatial.org/book/07-Introsf.html#sec-sfintro</a></p>
<p>Claudia Engel. Using Spatial Data with R. <a href="https://cengel.github.io/R-spatial/" class="uri">https://cengel.github.io/R-spatial/</a></p>
</div>
<div id="characteristics-of-spatial-data" class="section level2" number="21.3">
<h2>
<span class="header-section-number">21.3</span> Characteristics of spatial data<a class="anchor" aria-label="anchor" href="#characteristics-of-spatial-data"><i class="fas fa-link"></i></a>
</h2>
<p>For this lesson, I assume you have some working knowledge or experience working with
spatial information. You might have collected waypoints while working in the field,
plugged coordinates into Google Maps, or worked extensively with spatial data in
a GIS. This lesson will not cover spatial <em>analysis</em> – that is a whole course
in itself. Instead, the goal of this lesson is for you to be able to read, manipulate,
and plot data that has a spatial component, focusing on points.</p>
<p>Data with a spatial component is simply data that has coordinates associated with
it. These data can be points (e.g., an organism’s location), lines (e.g., an
animal’s movement trajectory), polygons (e.g., the boundaries of a study site).
These three types of data are called <strong>vector data</strong> (also called feeatures).
Here, <em>vector</em> means something different than it usually does in R; rather than
a series of elements of the same type, it means that the data is defined by coordinate
pairs: the pairs of coordinates that define points or vertices. Spatial data can
also come in a <strong>raster</strong>, or gridded, format, in which case a region is divided
into rectangles of the same size, each of which is associated with a value. We will
mainly focus on vector data in this lesson.</p>
</div>
<div id="the-sf-package" class="section level2" number="21.4">
<h2>
<span class="header-section-number">21.4</span> The <code>sf</code> package<a class="anchor" aria-label="anchor" href="#the-sf-package"><i class="fas fa-link"></i></a>
</h2>
<p>The <code>sf</code> package is the primary R package for manipulating spatial data. “sf” stands
for “simple features,” which is the structure for storing and accessing vector
data through the package. The <code>sf</code> package superceded the <code>sp</code> package, so if you
find functions on StackOverflow or other sources that use functions starting with
<code>sp</code>, know that these are currently not recommended for use.</p>
<p>At its core, you can think of an <code>sf</code> object as an extension of a data frame
or tibble. It contains a column (similar to a list-column) with information about
the features (or <em>geometries</em>). Here’s an example of a shapefile with points representing
centroids (center points) of Georgia counties:</p>
<div class="sourceCode" id="cb725"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb726"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">ga_counties_point</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "sf"         "data.frame"</code></pre>
<p>This is an <code>sf</code> object and also a data frame. Looking at the first few rows of data:</p>
<div class="sourceCode" id="cb728"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">ga_counties_point</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 3 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -84.49417 ymin: 31.03786 xmax: -81.44214 ymax: 34.88169
## Geodetic CRS:  WGS 84
##     NAME10                    Reg_Comm Sq_Miles                   geometry
## 1   Lanier            Southern Georgia  199.803 POINT (-83.06265 31.03786)
## 2    Bryan Coastal Regional Commission  455.108 POINT (-81.44214 32.01314)
## 3  Appling   Heart of Georgia Altamaha  512.558 POINT (-82.28893 31.74921)
## 4    Rabun           Georgia Mountains  376.854 POINT (-83.40222 34.88169)
## 5 Bleckley   Heart of Georgia Altamaha  219.121 POINT (-83.32789 32.43442)
## 6  Fayette Atlanta Regional Commission  199.286  POINT (-84.49417 33.4139)</code></pre>
<p>You can see that there are columns giving us the name area, and associated regional
commission for each county, but also a <code>geometry</code> column that contains a series
of features called <code>POINT</code>, each of which has an associated latitude and longitude.
Similarly, a different object that contains <em>polygons</em> representing county boundaries
looks like this:</p>
<div class="sourceCode" id="cb730"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">ga_counties_poly</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 3 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -84.62722 ymin: 30.84471 xmax: -81.13833 ymax: 35.00067
## Geodetic CRS:  WGS 84
##     NAME10                    Reg_Comm Sq_Miles                       geometry
## 1   Lanier            Southern Georgia  199.803 MULTIPOLYGON (((-83.0428 30...
## 2    Bryan Coastal Regional Commission  455.108 MULTIPOLYGON (((-81.40496 3...
## 3  Appling   Heart of Georgia Altamaha  512.558 MULTIPOLYGON (((-82.46585 3...
## 4    Rabun           Georgia Mountains  376.854 MULTIPOLYGON (((-83.61831 3...
## 5 Bleckley   Heart of Georgia Altamaha  219.121 MULTIPOLYGON (((-83.30089 3...
## 6  Fayette Atlanta Regional Commission  199.286 MULTIPOLYGON (((-84.55744 3...</code></pre>
<p>Here, each feature contains many coordinates, each of which is a vertex of the polygon.
In addition, printing the object to the screen tells us about some characteristics
of the data, including its projection (see below), the types of geometries it
contains (point, polygon, etc.), and its bounding box (the minimum and maximum
X and Y coordinates).</p>
<p>The <code>geometry</code> column acts differently from other columns in tibbles or data frames
because it is “locked”; you cannot un-select it:</p>
<div class="sourceCode" id="cb732"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># This does not work</span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">ga_counties_point</span>, <span class="op">-</span><span class="va">geometry</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 3 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -84.49417 ymin: 31.03786 xmax: -81.44214 ymax: 34.88169
## Geodetic CRS:  WGS 84
##     NAME10                    Reg_Comm Sq_Miles                   geometry
## 1   Lanier            Southern Georgia  199.803 POINT (-83.06265 31.03786)
## 2    Bryan Coastal Regional Commission  455.108 POINT (-81.44214 32.01314)
## 3  Appling   Heart of Georgia Altamaha  512.558 POINT (-82.28893 31.74921)
## 4    Rabun           Georgia Mountains  376.854 POINT (-83.40222 34.88169)
## 5 Bleckley   Heart of Georgia Altamaha  219.121 POINT (-83.32789 32.43442)
## 6  Fayette Atlanta Regional Commission  199.286  POINT (-84.49417 33.4139)</code></pre>
<p>However, otherwise <code>sf</code> objects can be used with filtering, selecting, and joining
operations just like you would with any other data frame:</p>
<div class="sourceCode" id="cb734"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Some examples</span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">ga_counties_point</span>, <span class="va">NAME10</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Clarke"</span>, <span class="st">"Oconee"</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div>
<pre><code>## Simple feature collection with 2 features and 3 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -83.43698 ymin: 33.83493 xmax: -83.36731 ymax: 33.95117
## Geodetic CRS:  WGS 84
##   NAME10          Reg_Comm Sq_Miles                   geometry
## 1 Clarke Northeast Georgia  121.027 POINT (-83.36731 33.95117)
## 2 Oconee Northeast Georgia  186.355 POINT (-83.43698 33.83493)</code></pre>
<div class="sourceCode" id="cb736"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">ga_counties_point</span>, <span class="va">NAME10</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 3 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -84.44473 ymin: 31.29713 xmax: -82.28893 ymax: 34.35411
## Geodetic CRS:  WGS 84
##     NAME10                  Reg_Comm Sq_Miles                   geometry
## 1  Appling Heart of Georgia Altamaha  512.558 POINT (-82.28893 31.74921)
## 2 Atkinson          Southern Georgia  344.592 POINT (-82.87996 31.29713)
## 3    Bacon          Southern Georgia  285.951 POINT (-82.45265 31.55367)
## 4    Baker         Southwest Georgia  349.074 POINT (-84.44473 31.32617)
## 5  Baldwin            Middle Georgia  267.405 POINT (-83.24982 33.06895)
## 6    Banks         Georgia Mountains  233.861 POINT (-83.49734 34.35411)</code></pre>
<p>Because the <code>geometry</code> column is locked, it can act unexpectedly during grouping
operations:</p>
<div class="sourceCode" id="cb738"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ga_counties_point</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">Reg_Comm</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/context.html">n</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 2 fields
## Geometry type: MULTIPOINT
## Dimension:     XY
## Bounding box:  xmin: -84.76798 ymin: 30.92246 xmax: -81.0923 ymax: 34.91666
## Geodetic CRS:  WGS 84
## # A tibble: 6 × 3
##   Reg_Comm                        n                                     geometry
##   &lt;chr&gt;                       &lt;int&gt;                             &lt;MULTIPOINT [°]&gt;
## 1 Atlanta Regional Commission    10 ((-84.15418 33.45298), (-84.49417 33.4139),…
## 2 Central Savannah River Area    13 ((-83.00106 33.2702), (-82.87877 33.56608),…
## 3 Coastal Regional Commission    10 ((-81.49362 31.21324), (-81.63629 30.92246)…
## 4 Georgia Mountains              13 ((-82.96425 34.35087), (-83.22921 34.37541)…
## 5 Heart of Georgia Altamaha      17 ((-82.28893 31.74921), (-82.63703 31.80558)…
## 6 Middle Georgia                 11 ((-83.17122 32.80236), (-83.42707 32.66713)…</code></pre>
<p>Here, by grouping by regional commission name, we have compressed all the county
centroids into a single MULTIPOINT geometry.</p>
<p>To remove the <code>geometry</code> column and convert the <code>sf</code> object back to a non-spatial
object, use <code><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_drop_geometry()</a></code>:</p>
<div class="sourceCode" id="cb740"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ga_counties_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_geometry.html">st_drop_geometry</a></span><span class="op">(</span><span class="va">ga_counties_point</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">ga_counties_df</span><span class="op">)</span></span></code></pre></div>
<pre><code>##     NAME10                    Reg_Comm Sq_Miles
## 1   Lanier            Southern Georgia  199.803
## 2    Bryan Coastal Regional Commission  455.108
## 3  Appling   Heart of Georgia Altamaha  512.558
## 4    Rabun           Georgia Mountains  376.854
## 5 Bleckley   Heart of Georgia Altamaha  219.121
## 6  Fayette Atlanta Regional Commission  199.286</code></pre>
<div class="sourceCode" id="cb742"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/class.html">class</a></span><span class="op">(</span><span class="va">ga_counties_df</span><span class="op">)</span></span></code></pre></div>
<pre><code>## [1] "data.frame"</code></pre>
</div>
<div id="map-projections-and-coordinate-reference-systems" class="section level2" number="21.5">
<h2>
<span class="header-section-number">21.5</span> Map projections and coordinate reference systems<a class="anchor" aria-label="anchor" href="#map-projections-and-coordinate-reference-systems"><i class="fas fa-link"></i></a>
</h2>
<p>The globe is round but we make plots and measurements in two-dimensional space.
Doing so inevitably creates some distortion in distance, area, and/or shape. For
example, consider common some global map projections:</p>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-10-1.png" width="672"></div>
<p>Each of these has different features, whether creating straight lines for
navigation (Mercator), distances between points (Azimuthal), or areas of polygons
(Mollweide). Except for the geographic coordinates, whose units are degrees of
latitude and longitude, all of these projections measure X and Y in meters. Another
common projection system is the Universal Transverse Mercator (UTM), where you
will usually see coordinates labeled “northing” and “easting”. UTMs are useful
because the system divides the Earth into zones, which results is less distortion
within each zone. However, this property means that UTMs are less useful for
continental or global-scale maps, since distortion is enhanced outside the zone.
When using UTMs, you need to know not only the northing and easting, but also
which zone was used to create the coordinates.</p>
<p><a href="https://doi.org/10.3133/70047422">This report from the U.S. Geological Survey</a>
provides an overview of some common projections.</p>
<p>Projections are identified using their coordinate reference system (CRS), which is a
set of information defining how to locate coordinates on a map relative to their
actual location on the three-dimensional globe. We can look at these properties of
an <code>sf</code> object using the <code><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs()</a></code> function.</p>
<div class="sourceCode" id="cb744"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">ga_counties_point</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: epsg:4326 
##   wkt:
## GEOGCRS["WGS 84",
##     ENSEMBLE["World Geodetic System 1984 ensemble",
##         MEMBER["World Geodetic System 1984 (Transit)"],
##         MEMBER["World Geodetic System 1984 (G730)"],
##         MEMBER["World Geodetic System 1984 (G873)"],
##         MEMBER["World Geodetic System 1984 (G1150)"],
##         MEMBER["World Geodetic System 1984 (G1674)"],
##         MEMBER["World Geodetic System 1984 (G1762)"],
##         MEMBER["World Geodetic System 1984 (G2139)"],
##         MEMBER["World Geodetic System 1984 (G2296)"],
##         ELLIPSOID["WGS 84",6378137,298.257223563,
##             LENGTHUNIT["metre",1]],
##         ENSEMBLEACCURACY[2.0]],
##     PRIMEM["Greenwich",0,
##         ANGLEUNIT["degree",0.0174532925199433]],
##     CS[ellipsoidal,2],
##         AXIS["geodetic latitude (Lat)",north,
##             ORDER[1],
##             ANGLEUNIT["degree",0.0174532925199433]],
##         AXIS["geodetic longitude (Lon)",east,
##             ORDER[2],
##             ANGLEUNIT["degree",0.0174532925199433]],
##     USAGE[
##         SCOPE["Horizontal component of 3D system."],
##         AREA["World."],
##         BBOX[-90,-180,90,180]],
##     ID["EPSG",4326]]</code></pre>
<p>This contains a lot of information, and you don’t need to parse all of it. The last
bit of information (<code>ID["EPSG",4326]]</code>) tells you that the code for this CRS
is EPSG:4326. The first bit of information tells us that we are using geographic
coordinates (“GEOGCRS”) under the WGS 84 system, which is the most common form of
geographic coordinates (lat/long). If available, it can be helpful to pull out a
subset of this information using the proj4string:</p>
<div class="sourceCode" id="cb746"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">ga_counties_point</span><span class="op">)</span><span class="op">$</span><span class="va">proj4string</span></span></code></pre></div>
<pre><code>## [1] "+proj=longlat +datum=WGS84 +no_defs"</code></pre>
<p>Using <code>sf</code>, we can easily reproject data from one coordinate system to another
using the <code><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform()</a></code> function. If you know what coordinate system you want
to use, you can usually Google its name and “crs” to find the code. For example,
the code for the Web Mercator projection is EPSG:3857:</p>
<div class="sourceCode" id="cb748"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ga_counties_point_merc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="va">ga_counties_point</span>, crs <span class="op">=</span> <span class="st">"EPSG:3857"</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">ga_counties_point_merc</span><span class="op">)</span><span class="op">$</span><span class="va">proj4string</span></span></code></pre></div>
<pre><code>## [1] "+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs"</code></pre>
<p>Now, you see we are using a new coordinate system. If we look at the data itself,
you can see that the coordinates have changed from decimal degrees to meters:</p>
<div class="sourceCode" id="cb750"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">ga_counties_point_merc</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 3 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -9405848 ymin: 3637666 xmax: -9066098 ymax: 4147815
## Projected CRS: WGS 84 / Pseudo-Mercator
##     NAME10                    Reg_Comm Sq_Miles                 geometry
## 1   Lanier            Southern Georgia  199.803 POINT (-9246492 3637666)
## 2    Bryan Coastal Regional Commission  455.108 POINT (-9066098 3765036)
## 3  Appling   Heart of Georgia Altamaha  512.558 POINT (-9160362 3730435)
## 4    Rabun           Georgia Mountains  376.854 POINT (-9284292 4147815)
## 5 Bleckley   Heart of Georgia Altamaha  219.121 POINT (-9276018 3820472)
## 6  Fayette Atlanta Regional Commission  199.286 POINT (-9405848 3950373)</code></pre>
<p>Converting between projectionsis important for spatial analysis (e.g., overlaying
two datasets in different projections) and plotting (see examples above and methods
below).</p>
<p><a href="https://xkcd.com/977/">XKCD has also covered map projections.</a></p>
</div>
<div id="raster-data-and-the-terra-package" class="section level2" number="21.6">
<h2>
<span class="header-section-number">21.6</span> Raster data and the <code>terra</code> package<a class="anchor" aria-label="anchor" href="#raster-data-and-the-terra-package"><i class="fas fa-link"></i></a>
</h2>
<p>Raster data are much more compact than vector data. Instead of storing each rectangle
as a series of vertices with associated information, rasters can store information
about the grid (its starting point, cell size, dimensions, and a projection) and
couple that with a matrix that contains data. This avoids needing to store the
actual location of each individual cell; in doing so, you can have a raster that
contains thousands or millions of cells but takes up much less space than an
equivalent feature set. A raster can have one or multiple “bands”, which are
the data layers associated with each grid cell.</p>
<p>The modern package for dealing with raster data is <code>terra</code>. Like <code>sf</code>, <code>terra</code>
superceded an older package (<code>raster</code>), so be careful with StackOverflow pages
from before 2023.</p>
<p>Here is an example of a raster object that contains information on mean temperature
across the globe from the <a href="https://www.worldclim.org/data/worldclim21.html">WorldClim database</a>:</p>
<div class="sourceCode" id="cb752"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://rspatial.org/">terra</a></span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb753"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mean_temp</span></span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 1080, 2160, 1  (nrow, ncol, nlyr)
## resolution  : 0.1666667, 0.1666667  (x, y)
## extent      : -180, 180, -90, 90  (xmin, xmax, ymin, ymax)
## coord. ref. : lon/lat WGS 84 (EPSG:4326) 
## source      : wc2.1_10m_tavg_01.tif 
## name        : wc2.1_10m_tavg_01 
## min value   :          -45.8840 
## max value   :           34.0095</code></pre>
<p>Just this summary gives us a lot of information: the raster is a 1,080 by 2,160
grid across the globe (its extent is the full range of latitude and lontitude).
It is in the WGS84 geographic coordinate system and has a range of values between
-46 and 34 degrees. It doesn’t tell us information about the units of the values,
how the data was collected, etc.; we would need to use the metadata to learn this.</p>
<p>A simple call to <code><a href="https://rspatial.github.io/terra/reference/plot.html">plot()</a></code> will display the data:</p>
<div class="sourceCode" id="cb755"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">mean_temp</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-18-1.png" width="672"></div>
<p>Here’s what this looks like across Georgia:</p>
<div class="sourceCode" id="cb756"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">ga_ext</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/ext.html">ext</a></span><span class="op">(</span><span class="va">ga_counties_poly</span><span class="op">)</span> <span class="co">#Get the bounding box (extent) of the GA data</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">mean_temp</span>, ext <span class="op">=</span> <span class="va">ga_ext</span><span class="op">)</span> <span class="co">#Plot mean temperature in this box</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">ga_counties_poly</span><span class="op">$</span><span class="va">geometry</span>, add <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="co">#Add the counties to this map</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-19-1.png" width="672"></div>
<p>And across Clarke county:</p>
<div class="sourceCode" id="cb757"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">clarke_poly</span> <span class="op">&lt;-</span> <span class="va">ga_counties_poly</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">NAME10</span> <span class="op">==</span> <span class="st">"Clarke"</span><span class="op">)</span></span>
<span><span class="va">clarke_ext</span> <span class="op">&lt;-</span>  <span class="fu"><a href="https://rspatial.github.io/terra/reference/ext.html">ext</a></span><span class="op">(</span><span class="va">clarke_poly</span><span class="op">)</span> <span class="co">#Get the bounding box (extent) of Clarke cty</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">mean_temp</span>, ext <span class="op">=</span> <span class="va">clarke_ext</span><span class="op">)</span> <span class="co">#Plot mean temperature in this box</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">clarke_poly</span><span class="op">$</span><span class="va">geometry</span>, add <span class="op">=</span> <span class="cn">T</span><span class="op">)</span> <span class="co">#Add the counties to this map</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-20-1.png" width="672"></div>
<p>This is where you start to see the grid size - Clarke county is so small that
it only contains two grid cells of this raster (at 0.17 degree resolution,
roughly 15 km). If we wanted to do an analysis or make a plot at this scale,
we would probably want to use higher-resolution raster data.</p>
<p>Just like with feature data, it is possible to reproject a raster, using the
<code><a href="https://rspatial.github.io/terra/reference/project.html">project()</a></code> function in <code>terra</code>:</p>
<div class="sourceCode" id="cb758"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mean_temp_merc</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/project.html">project</a></span><span class="op">(</span><span class="va">mean_temp</span>, <span class="st">"EPSG:3857"</span><span class="op">)</span></span>
<span><span class="va">mean_temp_merc</span></span></code></pre></div>
<pre><code>## class       : SpatRaster 
## dimensions  : 2407, 199, 1  (nrow, ncol, nlyr)
## resolution  : 200527.4, 201540.1  (x, y)
## extent      : -20037508, 19867438, -242578415, 242528681  (xmin, xmax, ymin, ymax)
## coord. ref. : WGS 84 / Pseudo-Mercator (EPSG:3857) 
## source(s)   : memory
## name        : wc2.1_10m_tavg_01 
## min value   :         -43.92729 
## max value   :          33.00763</code></pre>
<p>However, reprojecting rasters is a little more complicated than reprojecting
features/vectors, because we need to make assumptions about how to re-draw the grid
and how to assign new values to the new grid cells. This is why the minimum and
maximum values of <code>mean_temp_merc</code> differ from those in <code>mean_temp</code>; the function
made some assumptions about how to combine values when cells in the new grid contained
multiple cells from the old grid.</p>
</div>
<div id="reading-and-writing-spatial-data-outside-of-r" class="section level2" number="21.7">
<h2>
<span class="header-section-number">21.7</span> Reading and writing: spatial data outside of R<a class="anchor" aria-label="anchor" href="#reading-and-writing-spatial-data-outside-of-r"><i class="fas fa-link"></i></a>
</h2>
<div id="reading-and-creating-vectorsfeatures" class="section level3" number="21.7.1">
<h3>
<span class="header-section-number">21.7.1</span> Reading and creating vectors/features<a class="anchor" aria-label="anchor" href="#reading-and-creating-vectorsfeatures"><i class="fas fa-link"></i></a>
</h3>
<p>Vector data outside of R is most often stored as a shapefile with the extension
<code>.shp</code>. <code>sf</code> can load spatial data with other file extensions (e.g., <code>.gpx</code>,
<code>kml</code>, <code>.gpkg</code>). Load the data with the function <code><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read()</a></code>, which will then
provide information about the object you just read:</p>
<div class="sourceCode" id="cb760"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Read in polygon data of GA counties</span></span>
<span><span class="va">ga_counties_raw</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">"data/raw/Georgia_Counties/Georgia_Counties.shp"</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Reading layer `Georgia_Counties' from data source 
##   `/Users/cst80488/Library/CloudStorage/OneDrive-UniversityofGeorgia/Teaching/DataMgmt/DataMgmt_book/data/raw/Georgia_Counties/Georgia_Counties.shp' 
##   using driver `ESRI Shapefile'
## Simple feature collection with 159 features and 22 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: -373971.6 ymin: 129391.4 xmax: 1094729 ymax: 1831135
## Projected CRS: NAD83 / Georgia East (ftUS)</code></pre>
<p>You can also create an <code>sf</code> object from data with coordinates as columns using
<code><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf()</a></code>:</p>
<div class="sourceCode" id="cb762"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Our coordinate information about the `penguins` islands:</span></span>
<span><span class="va">island_info</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>island_name <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Torgersen"</span>, <span class="st">"Biscoe"</span>, <span class="st">"Dream"</span><span class="op">)</span>,</span>
<span>                          area_sqkm <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0.126</span>, <span class="fl">478.38</span>, <span class="fl">1.678</span><span class="op">)</span>,</span>
<span>                          long <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">64.0833</span>, <span class="op">-</span><span class="fl">65.9164</span>, <span class="op">-</span><span class="fl">64.2333</span><span class="op">)</span>,</span>
<span>                          lat <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">-</span><span class="fl">64.7667</span>, <span class="op">-</span><span class="fl">65.7474</span>, <span class="op">-</span><span class="fl">64.7333</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">island_info_sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="va">island_info</span>, coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"long"</span>,<span class="st">"lat"</span><span class="op">)</span>,</span>
<span>                           crs <span class="op">=</span> <span class="st">"epsg:4326"</span><span class="op">)</span></span>
<span><span class="va">island_info_sf</span></span></code></pre></div>
<pre><code>## Simple feature collection with 3 features and 2 fields
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: -65.9164 ymin: -65.7474 xmax: -64.0833 ymax: -64.7333
## Geodetic CRS:  WGS 84
##   island_name area_sqkm                  geometry
## 1   Torgersen     0.126 POINT (-64.0833 -64.7667)
## 2      Biscoe   478.380 POINT (-65.9164 -65.7474)
## 3       Dream     1.678 POINT (-64.2333 -64.7333)</code></pre>
<p>I specified the X and Y coordinates as a vector to the <code>coords</code> argument and
told the function what CRS to use, and I have an <code>sf</code> object with a <code>geometry</code>
column that replaced the columns <code>long</code> and <code>lat</code>. When reading a shapefile into
R, it is not necessary to specify the coordinate reference sysetm because that
information is embedded in the file.</p>
</div>
<div id="reading-and-creating-rasters" class="section level3" number="21.7.2">
<h3>
<span class="header-section-number">21.7.2</span> Reading and creating rasters<a class="anchor" aria-label="anchor" href="#reading-and-creating-rasters"><i class="fas fa-link"></i></a>
</h3>
<p>Raster data is often stored as an TIFF image (<code>.tif</code>), and larger rasters often
come in more compressed formats (e.g., NetCDF, <code>.nc</code>). Reading in a TIFF using
<code>terra</code> is as simple as including the file path within the <code><a href="https://rspatial.github.io/terra/reference/rast.html">rast()</a></code> function:</p>
<div class="sourceCode" id="cb764"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mean_temp</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span><span class="st">"data/raw/wc2.1_10m_tavg/wc2.1_10m_tavg_01.tif"</span><span class="op">)</span></span></code></pre></div>
<p>If a raster contains multiple layers, you can specify which to read using the
<code>layers</code> argument.</p>
<p>It is also possible to create a raster from scratch by specifying the dimensions,
extent, resoultion, and values. For example, if I wanted to create a 0.1-degree
resoultion raster that covers the extent of the <code>penguins</code> data, I might do this:</p>
<div class="sourceCode" id="cb765"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Create an empty raster</span></span>
<span><span class="va">penguins_gridded</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/rast.html">rast</a></span><span class="op">(</span>xmin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">island_info</span><span class="op">$</span><span class="va">long</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span>, xmax <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">island_info</span><span class="op">$</span><span class="va">long</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span>,</span>
<span>                         ymin <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">min</a></span><span class="op">(</span><span class="va">island_info</span><span class="op">$</span><span class="va">lat</span><span class="op">)</span><span class="op">-</span><span class="fl">1</span>, ymax <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/Extremes.html">max</a></span><span class="op">(</span><span class="va">island_info</span><span class="op">$</span><span class="va">lat</span><span class="op">)</span><span class="op">+</span><span class="fl">1</span>,</span>
<span>                         resolution <span class="op">=</span> <span class="fl">0.1</span>,</span>
<span>                         crs <span class="op">=</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/crs.html">crs</a></span><span class="op">(</span><span class="va">island_info_sf</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co"># Assign random values to the raster (in this case we don't have data to fill)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/values.html">values</a></span><span class="op">(</span><span class="va">penguins_gridded</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/Normal.html">rnorm</a></span><span class="op">(</span><span class="fu"><a href="https://rspatial.github.io/terra/reference/dimensions.html">ncell</a></span><span class="op">(</span><span class="va">penguins_gridded</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Look at the raster</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">penguins_gridded</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/plot.html">plot</a></span><span class="op">(</span><span class="va">island_info_sf</span><span class="op">$</span><span class="va">geometry</span>, add <span class="op">=</span> <span class="cn">T</span>, col <span class="op">=</span> <span class="st">"red"</span>, pch <span class="op">=</span> <span class="fl">19</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-25-1.png" width="672"></div>
</div>
<div id="writing-spatial-data-to-files" class="section level3" number="21.7.3">
<h3>
<span class="header-section-number">21.7.3</span> Writing spatial data to files<a class="anchor" aria-label="anchor" href="#writing-spatial-data-to-files"><i class="fas fa-link"></i></a>
</h3>
<p>To write vector graphics, use <code><a href="https://r-spatial.github.io/sf/reference/st_write.html">sf::st_write()</a></code>. The function will use the file
extension you supply to infer what type of file to write.</p>
<div class="sourceCode" id="cb766"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_write.html">st_write</a></span><span class="op">(</span><span class="va">island_info_sf</span>, <span class="st">"data/clean/penguin_island_points.shp"</span><span class="op">)</span> <span class="co"># Creates a shapefile</span></span>
<span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_write.html">st_write</a></span><span class="op">(</span><span class="va">island_info_sf</span>, <span class="st">"data/clean/penguin_island_points.kml"</span><span class="op">)</span> <span class="co"># Creates a KML</span></span></code></pre></div>
<p>Note that if you write to a shapefile, R will also create files with the extensions
<code>.prj.</code>, <code>.shx</code>, and <code>.dbf</code>. These are part of ESRI’s shapefile format and provide
additional data (for example, the projection or associated names/data).</p>
<p>To write a raster, use <code><a href="https://rspatial.github.io/terra/reference/writeRaster.html">terra::writeRaster()</a></code> or <code><a href="https://rspatial.github.io/terra/reference/writeCDF.html">terra::writeCDF()</a></code>:</p>
<div class="sourceCode" id="cb767"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://rspatial.github.io/terra/reference/writeRaster.html">writeRaster</a></span><span class="op">(</span><span class="va">penguins_gridded</span>, <span class="st">"data/clean/penguin_random_raster.tif"</span><span class="op">)</span></span></code></pre></div>
<p>Both <code><a href="https://r-spatial.github.io/sf/reference/st_write.html">st_write()</a></code> and <code><a href="https://rspatial.github.io/terra/reference/writeRaster.html">writeRaster()</a></code> have safeguards in place to ensure you don’t
accidentally overwrite your files. <code><a href="https://r-spatial.github.io/sf/reference/st_write.html">st_write()</a></code> gives you the option to append
information (i.e., add it to the existing file, <code>append = TRUE</code>) or overwrite it
(<code>append = FALSE</code>). In <code><a href="https://rspatial.github.io/terra/reference/writeRaster.html">writeRaster()</a></code>, use <code>overwrite = TRUE</code> to overwrite an
exsiting file.</p>
</div>
</div>
<div id="plotting-spatial-data-using-ggplot2" class="section level2" number="21.8">
<h2>
<span class="header-section-number">21.8</span> Plotting spatial data using <code>ggplot2</code><a class="anchor" aria-label="anchor" href="#plotting-spatial-data-using-ggplot2"><i class="fas fa-link"></i></a>
</h2>
<p><code>ggplot2</code> interfaces cleanly with the <code>sf</code> package by providing a geometry type
for <code>sf</code> objects. For example, to plot Georgia county centroids, we can use:</p>
<div class="sourceCode" id="cb768"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ga_counties_point</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-28-1.png" width="672"></div>
<p>Although this map could also be achieved using just latitude and longitude, the
plot now automatically labels axes with degrees, and uses a 1:1 axis ratio instead
of fitting the plot to the window size. This function also works with polygons:</p>
<div class="sourceCode" id="cb769"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ga_counties_poly</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-29-1.png" width="672"></div>
<p>In most other ways, this acts like a regular ggplot. For example, we can color
our features by a column:</p>
<div class="sourceCode" id="cb770"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">ga_counties_poly</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="va">Reg_Comm</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-30-1.png" width="672"></div>
<p>Rasters are less easily supported using <code>ggplot2</code>; it is easiest to first convert
them to a long-form data frame.</p>
<div class="sourceCode" id="cb771"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Crop January temperature raster to the extent to Georgia</span></span>
<span><span class="va">mean_temp_ga</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/crop.html">crop</a></span><span class="op">(</span><span class="va">mean_temp</span>, <span class="va">ga_counties_poly</span><span class="op">)</span></span>
<span><span class="co"># Convert to a data frame</span></span>
<span><span class="va">mean_temp_ga_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rspatial.github.io/terra/reference/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="va">mean_temp_ga</span>, xy <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rspatial.github.io/terra/reference/headtail.html">head</a></span><span class="op">(</span><span class="va">mean_temp_ga_df</span><span class="op">)</span></span></code></pre></div>
<pre><code>##           x        y wc2.1_10m_tavg_01
## 1 -85.58333 34.91667           2.96000
## 2 -85.41667 34.91667           3.10475
## 3 -85.25000 34.91667           3.58500
## 4 -85.08333 34.91667           3.43375
## 5 -84.91667 34.91667           3.49200
## 6 -84.75000 34.91667           3.47875</code></pre>
<p>Now, we have the X and Y coordinates of each raster cell along with its value.
For convenience, I will rename this column before plotting the raster.</p>
<div class="sourceCode" id="cb773"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="va">mean_temp_ga_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span><span class="va">mean_temp_ga_df</span>, jan_temp <span class="op">=</span> <span class="va">wc2.1_10m_tavg_01</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_tile</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mean_temp_ga_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, fill <span class="op">=</span> <span class="va">jan_temp</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-32-1.png" width="672"></div>
<p>We can also combine the data types to overlay the data:</p>
<div class="sourceCode" id="cb774"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_tile</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">mean_temp_ga_df</span>, <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="va">x</span>, y <span class="op">=</span> <span class="va">y</span>, fill <span class="op">=</span> <span class="va">jan_temp</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggsf.html">geom_sf</a></span><span class="op">(</span>data <span class="op">=</span> <span class="va">ga_counties_poly</span>, fill <span class="op">=</span> <span class="cn">NA</span>, color <span class="op">=</span> <span class="st">"black"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/scale_viridis.html">scale_fill_viridis_c</a></span><span class="op">(</span><span class="st">"Mean temperature\nin January (°C)"</span>, option <span class="op">=</span> <span class="st">"magma"</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_void</a></span><span class="op">(</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="spatial_files/figure-html/unnamed-chunk-33-1.png" width="672"></div>
</div>
<div id="other-topics" class="section level2" number="21.9">
<h2>
<span class="header-section-number">21.9</span> Other topics<a class="anchor" aria-label="anchor" href="#other-topics"><i class="fas fa-link"></i></a>
</h2>
<p>We have barely touched the surface of what you can do with spatial data in R. This
lesson ends here, but if you are a GIS whiz…know that you can do almost everything
you already know how to do in R (though it may not always be as efficient). Here
are some topics we didn’t cover but might interest you:</p>
<ul>
<li>creating rasters and features from scratch (instead of reading them in)</li>
<li>different object types in the <code>sf</code> world ()</li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="lists.html"><span class="header-section-number">20</span> Complex Data Structures in R</a></div>
<div class="empty"></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#spatial"><span class="header-section-number">21</span> An Introduction to Spatial Data in R</a></li>
<li><a class="nav-link" href="#objectives-18"><span class="header-section-number">21.1</span> Objectives</a></li>
<li><a class="nav-link" href="#additional-reading-15"><span class="header-section-number">21.2</span> Additional reading</a></li>
<li><a class="nav-link" href="#characteristics-of-spatial-data"><span class="header-section-number">21.3</span> Characteristics of spatial data</a></li>
<li><a class="nav-link" href="#the-sf-package"><span class="header-section-number">21.4</span> The sf package</a></li>
<li><a class="nav-link" href="#map-projections-and-coordinate-reference-systems"><span class="header-section-number">21.5</span> Map projections and coordinate reference systems</a></li>
<li><a class="nav-link" href="#raster-data-and-the-terra-package"><span class="header-section-number">21.6</span> Raster data and the terra package</a></li>
<li>
<a class="nav-link" href="#reading-and-writing-spatial-data-outside-of-r"><span class="header-section-number">21.7</span> Reading and writing: spatial data outside of R</a><ul class="nav navbar-nav">
<li><a class="nav-link" href="#reading-and-creating-vectorsfeatures"><span class="header-section-number">21.7.1</span> Reading and creating vectors/features</a></li>
<li><a class="nav-link" href="#reading-and-creating-rasters"><span class="header-section-number">21.7.2</span> Reading and creating rasters</a></li>
<li><a class="nav-link" href="#writing-spatial-data-to-files"><span class="header-section-number">21.7.3</span> Writing spatial data to files</a></li>
</ul>
</li>
<li><a class="nav-link" href="#plotting-spatial-data-using-ggplot2"><span class="header-section-number">21.8</span> Plotting spatial data using ggplot2</a></li>
<li><a class="nav-link" href="#other-topics"><span class="header-section-number">21.9</span> Other topics</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Data Management and Reproducible Science</strong>" was written by Claire S Teitelbaum. It was last built on 2025-11-08.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
